version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15
    container_name: url-shortener-db
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test@123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-db.sql:/docker-entrypoint-initdb.d/00-init-db.sql
      - ./backend/generate-sample-data.sql:/docker-entrypoint-initdb.d/01-sample-data.sql
      - ./backend/generate-click-events.sql:/docker-entrypoint-initdb.d/02-click-events.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d url_shortener"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: url-shortener-redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Gateway
  api-gateway:
    build:
      context: ./backend
      dockerfile: api-gateway/Dockerfile
    container_name: url-shortener-gateway
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379

  # Shortening Service
  shortening-service:
    build:
      context: ./backend
      dockerfile: shortening-service/Dockerfile
    container_name: url-shortener-shortening
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/url_shortener
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=test@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # Redirect Analytics Service
  redirect-analytics-service:
    build:
      context: ./backend
      dockerfile: redirect-analytics-service/Dockerfile
    container_name: url-shortener-analytics
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/url_shortener
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=test@123
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: url-shortener-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

volumes:
  postgres_data: