server:
  port: 8081

spring:
  application:
    name: shortening-service
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    driver-class-name: org.postgresql.Driver
    username: admin
    password: test@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect