server:
  port: 8082

spring:
  application:
    name: redirect-analytics-service
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    driver-class-name: org.postgresql.Driver
    username: admin
    password: test@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms